import createClient from "openapi-fetch/src/index.js";
import type { paths } from "../types/schema"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "/api" });

export { client }